variables:
        appFilePath: $(System.DefaultWorkingDirectory)/app/build/outputs/apk/debug/app-debug.apk
        testFilePath: $(System.DefaultWorkingDirectory)/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
        bsDevice: Samsung Galaxy S22 Ultra
        bsOsVersion: 12.0
pool:
  vmImage: 'ubuntu-latest'
steps:
  - task: BrowserStackConfig@0
    inputs:
      BrowserStackServiceEndPoint: 'bstack-conn'
  
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo $BROWSERSTACK_USERNAME
        echo $BROWSERSTACK_ACCESS_KEY
        output=$(curl -u $BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY -X POST https://api-cloud.browserstack.com/app-automate/espresso/v2/app -F "file=@app-debug.apk" -F "data={\"custom_id\":\"demoapp\"}")
        echo "1er script - voici l'output : " $output
        echo $output | python -c 'import sys, json; print(json.load(sys.stdin)["app_url"])' > apk_url.txt
        echo "DEBUT voici le contenu du cat apk_url.txt"
        cat apk_url.txt
        echo "FIN voici le contenu du cat apk_url.txt"

        outputtest=$(curl -u $BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY -X POST https://api-cloud.browserstack.com/app-automate/espresso/v2/test-suite -F file=@app-debug-androidTest.apk)
        echo "2eme script - voici l'output : " $outputtest
        echo $outputtest | python -c 'import sys, json; print(json.load(sys.stdin)["test_suite_url"])' > apk_test_url.txt
        echo "DEBUT voici le contenu du cat apk_test_url.txt"
        cat apk_test_url.txt
        echo "FIN voici le contenu du cat apk_test_url.txt"
        echo $(curl -u $BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY -X POST https://api-cloud.browserstack.com/app-automate/espresso/v2/build -d "{\"app\": \"bs://7f5151e1039757e83f3d61258ad31fe22f624dfe\", \"device\": \"$(bsDevice)\", \"device_os\": \"Samsung Galaxy S22\", \"test_suite\": \"bs://dcf948fc4c6cec12d9a2554c384fcf64e32a0427\"}" -H "Content-Type: application/json")
        echo $run_test