variables:
        appFilePath: $(System.DefaultWorkingDirectory)/app/build/outputs/apk/debug/app-debug.apk
        testFilePath: $(System.DefaultWorkingDirectory)/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
        bsDevice: Samsung Galaxy S22 Ultra
        bsOsVersion: 12.0
pool:
  vmImage: 'ubuntu-latest'
steps:
  - task: BrowserStackConfig@0
    inputs:
      BrowserStackServiceEndPoint: 'bstack-conn'
  
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        output=$(curl -u $env:BROWSERSTACK_USERNAME:$env:BROWSERSTACK_ACCESS_KEY -X POST https://api-cloud.browserstack.com/app-automate/upload -F file=@app-debug.apk -F "data={\"custom_id\":\"demoapp\"}")
         echo $output
        #  outputtest=$(curl -u $env:BROWSERSTACK_USERNAME:$env:BROWSERSTACK_ACCESS_KEY -X POST https://api-cloud.browserstack.com/app-automate/espresso/v2/test-suite -F file=@$(testFilePath))
        #  echo $outputtest