# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'bstack-conn'
    
- script: |
    - task: Gradle@3
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'clean executeDebugTestsOnBrowserstack'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false
  displayName: 'Run a multi-line script'
